#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

./vendor/bin/pint --test ||
(
  echo 'Pint errors found. Please fix them before committing.'
  false;
)

./vendor/bin/sail artisan test ||
(
  echo 'Tests failed. Please fix them before committing.'
  false;
)

echo 'Committing this now. 🚀'

